#!/bin/bash
# Decrypt and repair PDF files.
# B. Nelissen
# Winter 2012-2013

# ask for folder
if [ ! -f "$1" ];
then
  # no directory found, exit with error
  echo "No file found"
  echo "Use the script like:"
  echo "$(basename "$0") file.pdf"
  echo
  exit 1
fi

# convert all .pdf files in folder to .decrypted.pdf
# Local variables
OUTPUTEXTENSION=".decrypted.pdf"
FILE="$1"
DIRNAME="$(dirname "$FILE")"
BASENAME="$(basename "$FILE")" # filename with extension
FILENAME="${FILE%\.*}" # filename without extension
OUTPUTFILE="$FILENAME""$OUTPUTEXTENSION"
  
# actual command, move original when qpdf was successful
qpdf --decrypt "$FILE" "$OUTPUTFILE" && mv "$OUTPUTFILE" "$FILE"
