#!/bin/bash
# Share current folder using python simple http server.
# b.nelissen

PORT=80
LOCALIP=$(/sbin/ifconfig | grep '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | grep -v 127.0.0.1 | awk '{print $2}')

echo "Serving $(pwd)"
echo "http://${LOCALIP}:$PORT"
python -m SimpleHTTPServer $PORT